main: net.natroutter.betterchairs.BetterChairs
name: ${project.name}
version: ${project.version}
author: NATroutter
description: ${project.description}
api-version: 1.18
website: ${project.url}
depend: [NATLibs]